### ISSUE TITLE
Ros2 Publisher, Fastrtps Subscriber

### ISSUE THREAD

**Issue by golizheh** [eProsima/FIROS2#14]
Hi @LuisGP ,

I have setup my system in the follwoing way:
Helloworld.id: 

```cpp
struct HelloWorld
{
	
	string message;
};
```

I have Update Helloworld example and FIROS2 by using this new IDL file.
I have also update userlibb as follow:

```cpp
// Custom transformation
         
	//string_data.data_(helloworld_data.message());
	//std::cout << string_data.data_() << std::endl;
	string_data.data_()=helloworld_data.message();
	std::cout << string_data.data_() <<std::endl;
```

I have also update Config.XML file as we have had in the previous issue.

I have also Update Subscriber as follow:
```cpp
 if(sub->takeNextData((void*)&m_Hello, &m_info))
    {
        if(m_info.sampleKind == ALIVE)
        {
            this->n_samples++;
	std::cout <<"Message Gettt"<<std::endl;
            // Print your structure data here.
	if(m_info.sample_identity.writer_guid().guidPrefix==
                             sub->getGuid().guidPrefix)
                 {
std::cout <<"Message Gettt"<<std::endl;
                  }
```

When I run in ROS2 talker is publisher message and in Firoso2 I will get the following outcom:
```bash
Hello World: 4
Hello World: 0
Hello World: 2
Hello World: 13
Hello World: 15
Hello World: 14
Hello World: 0
...
```

But it my subscriber I will get nothing? Also as it is clear in FIROS2 console outcome are really out of order?

**Comment by LuisGP** [comment]
Hi @golizheh 

If you change the HelloWorld type in FIROS2, you must update the whole HelloWorld example to make use of it. FIROS2 needs to know how to serialize and deserialize what comes from each endpoint, that's why FIROS2's HelloWorld type must match HelloWorldExample type and FIROS2 String type must match ROS2 talker/listener example type.

If you change it only in the FIROS2 pub/sub, the serialization/deserialization will fail. In this case, seems that uninitialized memory is being shown.

To make it clear:
HelloWorldExample publisher type must be equal to FIROS2-FastRTPS-Subscriber type.
FIROS2-FastRTPS-Subscriber type must be the same as HelloWorldExample subscriber type.
ROS2 Talker type must be equal to FIROS2-ROS2-Subscriber type.
FIROS2-ROS2-Publisher type must be equal to ROS2 Listener type.

Additionally, the comparision of the guidPrefix `if(m_info.sample_identity.writer_guid().guidPrefix==sub->getGuid().guidPrefix)` isn't correct. The guidPrefix is an array of octets, so you must compare the full array. In this way you are only comparing the address of the first element, that probably will fail always.

**Comment by golizheh** [comment]
Dear @LuisGP 

I complete understand the two types should be equal to each other in order to read, 


Lets take a first hello world example with out any changes just like you have? could you show the update file of userlib.cpp and update part of subscriber class in fast rtps?

**Comment by golizheh** [comment]
As I test it several times with different config, as I can see, nothing is published from ROS2 because FIROS2 can not read anything and return empty.  
could you make in it clear by an example?

**Comment by golizheh** [comment]
Hi @LuisGP , 

I have updated Userlib.cpp as follow:

```cpp
extern "C" void USER_LIB_EXPORT transform_to_fastrtps(SerializedPayload_t *serialized_input, SerializedPayload_t *serialized_output){
// User types
	std_msgs::msg::dds_::String_ string_data;
	std_msgs::msg::dds_::String_PubSubType string_pst;
	HelloWorld helloworld_data;
	HelloWorldPubSubType helloworld_pst;
// Deserialization
	string_pst.deserialize(serialized_input, &helloworld_data);

// Custom transformation
//This part is not complete will be complete later

        std::cout << string_data.data_() << std::endl;
        std::cout << "Hello From Second Function" << std::endl;
// Serialization
	serialized_output->reserve(helloworld_pst.m_typeSize);
}
```

I think there is problem in serilization and deserilation. because when I run it I will get :
Segmentation fault (core dumped)

And it is because of deseriliazation. which varibale should I use here?

**Comment by LuisGP** [comment]
Hi @golizheh 

Sorry for the delay, but I was very busy with other tasks.
We cannot create a full example right now, but as you talked with @lemunozm at https://github.com/eProsima/SOSS-DDS/issues/20, the problem is very probably the serialization/deserialization. If you modify a type, `Helloworld` in this case, you must adapt the serialization and deserialization of the type in the HelloworldPubSubType files too. The easiest way to do it is to regenerate the type again from its IDL using Fast-RTPS-Gen. Of course, both HelloWorldExample and the FIROS2 example must be modified to make use of the new generated sources.

We saw you are trying to achieve the same result using both FIROS2 and SOSS. I recommend you to continue with SOSS, because FIROS2 was discontinued and there are no plans to update it.

**Comment by lemunozm** [comment]
Hi @golizheh, 

could I ask you about what is your aim using SOSS or FIROS in order to recommend you which of our technologies fix better for your use case? You can send me an email if you prefer at `luismunoz@eprosima.com`

**Comment by golizheh** [comment]
@lemunozm 

Email is sent to you, I will closs this issue and follow you with email .

Thanks
